"""
Django settings for learning_log project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*h^(u!=17@ve)b6ku&_k+-!qabc37**_24sj+u%q^p=gl)y0j3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # my apps
    'learning_logs',
    'users',

    # third party
    'bootstrap4',

    # default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'learning_log.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'learning_log.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# local sqlite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# local PostgreSQL
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',  # 数据库引擎
#         'NAME': 'mydb',  # 数据库名，Django不会帮你创建，需要自己进入数据库创建。
#         'USER': 'root',  # 设置的数据库用户名
#         'PASSWORD': 'admin',  # 设置的密码
#         'HOST': '127.0.0.1',  # 本地主机或数据库服务器的ip
#         'PORT': '5432',  # 数据库使用的端口
#     }
# }

# Render database test from external networks
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'learning_logs_e7h2',
#         'USER': 'learning_logs_e7h2_user',
#         'PASSWORD': 'JjJpNEfoZDtGhezLdqlXqLQjIJ9CDI86',
#         'HOST': 'dpg-covomq7jbltc73dhpf0g-a.singapore-postgres.render.com',
#         'PORT': '5432',
#     }
# }

# Render database
# external networks

# postgres://learning_logs_e7h2_user:JjJpNEfoZDtGhezLdqlXqLQjIJ9CDI86@dpg-covomq7jbltc73dhpf0g-a/learning_logs_e7h2
# USER= learning_logs_e7h2_user
# PASSWORD= JjJpNEfoZDtGhezLdqlXqLQjIJ9CDI86
# INTERNAL_HOST= dpg-covomq7jbltc73dhpf0g-a
# DATABASE= learning_logs_e7h2

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#
#         'HOST': 'dpg-covomq7jbltc73dhpf0g-a',
#         'PORT': '5432',
#
#         'NAME': 'learning_logs_e7h2',
#         'USER': 'learning_logs_e7h2_user',
#         'PASSWORD': 'JjJpNEfoZDtGhezLdqlXqLQjIJ9CDI86',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ....
LOGIN_URL = 'users:login'

# Heroku settings
import django_heroku
django_heroku.settings(locals())
